[package]
name = "starship-poc"
version = "0.1.0"
authors = ["Matan Kushner <hello@matchai.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.27"
clap = "2.33.0"
structopt = "0.3.11"
once_cell = "1.3.1"
pretty_env_logger = "0.4.0"
log = "0.4.8"
thiserror = "1.0.18"
serde = { version = "1.0.110", features = ["derive"] }
toml = "0.5.6"
dirs = "2.0.2"
lazy_static = "1.4.0"
ansi_term = "0.12.1"
cmd_lib = "0.12.0"

[dev-dependencies]
criterion = "0.3.2"

[profile.release]
debug = true

[[bench]]
name = "bench"
harness = false
